"""phase 6 application rule context snapshot

Revision ID: 0cfb3627b26f
Revises: 9b6a5cb597ee
Create Date: 2026-08-21 00:39:15.943443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cfb3627b26f'
down_revision: Union[str, Sequence[str], None] = '9b6a5cb597ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rule_context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rule_context_snapshot')
    # ### end Alembic commands ###
