"""phase 3 initial schema

Revision ID: 6e570d9a2c2e
Revises: 
Create Date: 2026-08-21 00:04:35.975491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e570d9a2c2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.String(length=64), nullable=False),
    sa.Column('applicant_type', sa.Enum('SALARIED', 'SELF_EMPLOYED', 'MSME', 'CORPORATE', name='applicant_type'), nullable=False),
    sa.Column('requested_loan_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('requested_tenure_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'DECISIONED', 'FAILED', name='application_status'), nullable=False),
    sa.Column('normalized_profile_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_vector_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_applicant_id'), 'applications', ['applicant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('eligibility_multipliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.Enum('INDIVIDUAL', 'MSME', name='applicant_pipeline'), nullable=False),
    sa.Column('risk_grade', sa.String(length=8), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cap_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_code', 'version', name='uq_elig_mult_code_version')
    )
    op.create_index(op.f('ix_eligibility_multipliers_config_code'), 'eligibility_multipliers', ['config_code'], unique=False)
    op.create_table('pricing_bands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('config_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.Enum('INDIVIDUAL', 'MSME', name='applicant_pipeline'), nullable=False),
    sa.Column('risk_grade', sa.String(length=8), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_code', 'version', name='uq_pricing_band_code_version')
    )
    op.create_index(op.f('ix_pricing_bands_config_code'), 'pricing_bands', ['config_code'], unique=False)
    op.create_table('recalibration_offsets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline', sa.Enum('INDIVIDUAL', 'MSME', name='applicant_pipeline'), nullable=False),
    sa.Column('risk_grade', sa.String(length=8), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('offset_value', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline', 'risk_grade', 'version', name='uq_recal_offset_pipeline_grade_version')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pipeline', sa.Enum('INDIVIDUAL', 'MSME', name='applicant_pipeline'), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('operator', sa.Enum('LT', 'LTE', 'GT', 'GTE', 'EQ', 'NEQ', 'IN', 'NOT_IN', 'IS_NULL', 'IS_NOT_NULL', name='rule_operator'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.Enum('HARD_REJECT', 'EXCEPTION', name='rule_outcome'), nullable=False),
    sa.Column('severity', sa.Enum('L1', 'L2', 'CREDIT_HEAD', name='exception_level'), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('rule_group', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code', 'version', name='uq_rules_code_version')
    )
    op.create_index(op.f('ix_rules_rule_code'), 'rules', ['rule_code'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.Enum('STP_APPROVED', 'HARD_REJECT', 'EXCEPTION_REQUIRED', 'INSUFFICIENT_DATA', name='decision_outcome'), nullable=False),
    sa.Column('risk_grade', sa.String(length=8), nullable=True),
    sa.Column('eligible_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tenure_months', sa.Integer(), nullable=True),
    sa.Column('model_risk_score', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('rule_version_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_decision_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_application_id'), 'decisions', ['application_id'], unique=False)
    op.create_table('exceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('L1', 'L2', 'CREDIT_HEAD', name='exception_level'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='exception_status'), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exceptions_decision_id'), 'exceptions', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exceptions_decision_id'), table_name='exceptions')
    op.drop_table('exceptions')
    op.drop_index(op.f('ix_decisions_application_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_rules_rule_code'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('recalibration_offsets')
    op.drop_index(op.f('ix_pricing_bands_config_code'), table_name='pricing_bands')
    op.drop_table('pricing_bands')
    op.drop_index(op.f('ix_eligibility_multipliers_config_code'), table_name='eligibility_multipliers')
    op.drop_table('eligibility_multipliers')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_applications_applicant_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###

    # autogenerate doesn't drop ENUM types shared across multiple tables
    # (applicant_pipeline, exception_level) until every table using them is
    # gone — done explicitly here so downgrade is actually the inverse of
    # upgrade, not "drop tables, leak types" (caught by hand-testing the
    # downgrade/upgrade round-trip, not assumed correct from autogenerate).
    for enum_name in (
        "applicant_type", "application_status", "applicant_pipeline",
        "rule_operator", "rule_outcome", "exception_level",
        "decision_outcome", "exception_status",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
