"""phase 5 weighted scoring config

Revision ID: 9b6a5cb597ee
Revises: 6e570d9a2c2e
Create Date: 2026-08-21 00:23:11.899364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9b6a5cb597ee'
down_revision: Union[str, Sequence[str], None] = '6e570d9a2c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False on 'pipeline': applicant_pipeline's Postgres ENUM
    # type already exists from the initial migration (it's also used by
    # rules/eligibility_multipliers/pricing_bands/recalibration_offsets) --
    # without this, SQLAlchemy re-issues CREATE TYPE for every table that
    # references an Enum column, even one it already created elsewhere.
    op.create_table('weighted_scoring_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pipeline', postgresql.ENUM('INDIVIDUAL', 'MSME', name='applicant_pipeline', create_type=False), nullable=False),
    sa.Column('source_field', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Enum('HIGHER_IS_RISK', 'LOWER_IS_RISK', name='risk_direction'), nullable=False),
    sa.Column('base_limit', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('reference_range', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('weight', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_code', 'version', name='uq_weighted_scoring_field_version')
    )
    op.create_index(op.f('ix_weighted_scoring_config_field_code'), 'weighted_scoring_config', ['field_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weighted_scoring_config_field_code'), table_name='weighted_scoring_config')
    op.drop_table('weighted_scoring_config')
    # ### end Alembic commands ###

    # risk_direction is new in this migration (unlike applicant_pipeline,
    # reused from the initial migration) -- drop it explicitly, per the
    # orphaned-enum-type lesson from the Phase 3 initial migration.
    sa.Enum(name="risk_direction").drop(op.get_bind(), checkfirst=True)
